### ISSUE TITLE
salt-checkin-module hangs

### ISSUE THREAD

**Issue by mm-johnpeterson** [salopensource/salt_checkin_module#1]
I added logging to figure out where this was failing (for me) and found:

In `def process_salt_logs(pid)` it appears there are seen_matches found. When these are added to the set everything just seems to stop. 

```
2019-12-10 12:27:05,117 [DEBUG] SaltySal: SALT_RETURNER_LOG: /usr/local/sal/salt_returner_results.json exists
2019-12-10 12:27:05,119 [DEBUG] SaltySal: Salt log exists at /var/log/salt/minion
2019-12-10 12:27:09,425 [DEBUG] SaltySal: Match found pattern, log
2019-12-10 12:27:09,425 [DEBUG] SaltySal: messages appended with: {'text': 'Insecure logging configuration detected! Sensitive data may be logged.', 'message_type': 'WARNING'}
2019-12-10 12:27:09,425 [DEBUG] SaltySal: seen_matches appended with: ('WARNING', 'Insecure logging configuration detected! Sensitive data may be logged.')
```

The fact I have debugging turned on for Salt shouldn't be causing the match to hang right?

**Comment by mm-johnpeterson** [comment]
Update: /usr/local/sal/salt_returner_results.json appears to be the issue. If I remove that file, call a high state, and run sal-submit there is no issue. This may be more of a Salt logging related issue.

**Comment by sheagcraig** [comment]
Hmmmm... So maybe there's something causing it to freak out from previous runs? Once you have removed the `salt_returner_results.json` and successfully run, does it complete successfully on subsequent runs as well?

**Comment by mm-johnpeterson** [comment]
I completely spaced that I have seen this before, right after I initially added Salt to the mix. I removed the `salt-returner-results.json` and `sal-submit` worked just fine. I didn't pay attention to it for a while and at some point, I guess, that json became problematic again. I'll keep an eye on it to see when it hangs next and then verify that `salt-returner-results.json` is valid json.

Would the parser bail or hang if there was a `None` as a value? I don't think that's the case, just trying to think of what might be causing the hang.

**Comment by sheagcraig** [comment]
It's all kind of early days for this; I'm the only person using it that I know of; maybe one other enterprise. So it could be _anything_!

**Comment by sheagcraig** [comment]
Hey @mm-johnpeterson; have you been rolling along with the updates? Is this still an issue?
